export const RANK_LEVELS = Object.freeze([
  {
    level: 0,
    label: 'VIP 0',
    shortLabel: 'VIP 0',
    depositStep: 0,
    totalDeposit: 0,
  },
  {
    level: 1,
    label: 'VIP 1',
    shortLabel: 'VIP 1',
    depositStep: 100,
    totalDeposit: 100,
  },
  {
    level: 2,
    label: 'VIP 2',
    shortLabel: 'VIP 2',
    depositStep: 200,
    totalDeposit: 300,
  },
  {
    level: 3,
    label: 'VIP 3',
    shortLabel: 'VIP 3',
    depositStep: 500,
    totalDeposit: 800,
  },
  {
    level: 4,
    label: 'VIP 4',
    shortLabel: 'VIP 4',
    depositStep: 1000,
    totalDeposit: 1800,
  },
  {
    level: 5,
    label: 'VIP 5',
    shortLabel: 'VIP 5',
    depositStep: 2000,
    totalDeposit: 3800,
  },
  {
    level: 6,
    label: 'VIP 6',
    shortLabel: 'VIP 6',
    depositStep: 5000,
    totalDeposit: 8800,
  },
  {
    level: 7,
    label: 'VIP 7',
    shortLabel: 'VIP 7',
    depositStep: 10000,
    totalDeposit: 18800,
  },
  {
    level: 8,
    label: 'VIP 8',
    shortLabel: 'VIP 8',
    depositStep: 30000,
    totalDeposit: 48800,
  },
  {
    level: 9,
    label: 'VIP 9',
    shortLabel: 'VIP 9',
    depositStep: 51200,
    totalDeposit: 100000,
  },
  {
    level: 10,
    label: 'VIP 10',
    shortLabel: 'VIP 10',
    depositStep: 900000,
    totalDeposit: 1000000,
  },
]);

export const RANK_REWARDS = Object.freeze([
  {
    level: 0,
    label: 'VIP 0',
    badgeColor: '#adb5bd',
    tagline: 'Старт',
    description: 'Базовый статус без дополнительных бонусов, доступ к стандартным акциям.',
    purpose: 'Познакомить игрока с сервисом и не перегружать его дополнительными условиями.',
  },
  {
    level: 1,
    label: 'VIP 1',
    badgeColor: '#cd7f32',
    tagline: 'Разгон',
    description: 'Персональные подборки игр и напоминания о бонусах в личных сообщениях.',
    purpose: 'Стимулировать первый возврат игрока и закрепить привычку заходить в казино.',
  },
  {
    level: 2,
    label: 'VIP 2',
    badgeColor: '#c0c0c0',
    tagline: 'Бонусный старт',
    description: 'Еженедельные бесплатные вращения и повышенные лимиты на пополнение.',
    purpose: 'Повысить активность за счёт регулярных наград и мягкого увеличения депозитов.',
  },
  {
    level: 3,
    label: 'VIP 3',
    badgeColor: '#d4af37',
    tagline: 'Быстрый вывод',
    description: 'Приоритетная обработка заявок на вывод и увеличенный кэшбэк по выходным.',
    purpose: 'Создать ощущение премиального сервиса и ускорить циклы депозитов-выводов.',
  },
  {
    level: 4,
    label: 'VIP 4',
    badgeColor: '#e5e4e2',
    tagline: 'Подарки',
    description: 'Подарки к праздникам и персональные предложения от менеджера рангов.',
    purpose: 'Поддерживать лояльность через персональные события и эмоции.',
  },
  {
    level: 5,
    label: 'VIP 5',
    badgeColor: '#b9f2ff',
    tagline: 'Персональный менеджер',
    description: 'Выделенный менеджер 24/7 и доступ в закрытые турниры с крупными призами.',
    purpose: 'Дать ощущение заботы и обеспечить прямой канал коммуникации для high-rollers.',
  },
  {
    level: 6,
    label: 'VIP 6',
    badgeColor: '#0f52ba',
    tagline: 'Повышенный кэшбэк',
    description: 'Увеличенный процент кэшбэка и эксклюзивные бонусы на крупные депозиты.',
    purpose: 'Поддерживать высокие обороты игроков с помощью ощутимой экономии.',
  },
  {
    level: 7,
    label: 'VIP 7',
    badgeColor: '#e0115f',
    tagline: 'Закрытые предложения',
    description: 'Участие в закрытых акциях и расширенные лимиты на вывод средств.',
    purpose: 'Сделать статус эксклюзивным и открыть доступ к редким активностям.',
  },
  {
    level: 8,
    label: 'VIP 8',
    badgeColor: '#50c878',
    tagline: 'Турнирный элитный',
    description: 'Персональные приглашения на офлайн-ивенты и премиальные подарки от казино.',
    purpose: 'Укрепить вовлечённость через соревнования и живое общение с брендом.',
  },
  {
    level: 9,
    label: 'VIP 9',
    badgeColor: '#4b0082',
    tagline: 'Королевский клуб',
    description: 'Максимальные лимиты, экспресс-вывод и эксклюзивные подарки каждый месяц.',
    purpose: 'Подчеркнуть элитарность и закрепить долгосрочную ценность для топовых игроков.',
  },
  {
    level: 10,
    label: 'VIP 10',
    badgeColor: '#212529',
    tagline: 'Легенда',
    description: 'Полный доступ ко всем привилегиям, индивидуальные условия и годовой подарок.',
    purpose: 'Отметить легендарный статус и поощрить максимальную вовлечённость в экосистему.',
  },
]);
