import { enrichAccountsWithTransactions } from './transactionsSeed';

const BASE_ACCOUNTS = [
  {
    id: 'seed-user-01',
    email: 'user01@dodepus.com',
    password: 'User01#Pass',
    role: 'user',
    extras: {
      nickname: 'LuckyOtter',
      firstName: 'Olivia',
      lastName: 'Stone',
      country: 'US',
      city: 'Las Vegas',
      balance: 1250,
      casinoBalance: 350,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-02',
    email: 'user02@dodepus.com',
    password: 'User02#Pass',
    role: 'user',
    extras: {
      nickname: 'BoldFalcon',
      firstName: 'Michael',
      lastName: 'Reeves',
      country: 'CA',
      city: 'Toronto',
      balance: 980,
      casinoBalance: 120,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-03',
    email: 'user03@dodepus.com',
    password: 'User03#Pass',
    role: 'user',
    extras: {
      nickname: 'SilverComet',
      firstName: 'Emma',
      lastName: 'Li',
      country: 'SG',
      city: 'Singapore',
      balance: 1500,
      casinoBalance: 620,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-04',
    email: 'user04@dodepus.com',
    password: 'User04#Pass',
    role: 'user',
    extras: {
      nickname: 'NeonRaven',
      firstName: 'Daniel',
      lastName: 'Kozlov',
      country: 'RU',
      city: 'Moscow',
      balance: 870,
      casinoBalance: 240,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-05',
    email: 'user05@dodepus.com',
    password: 'User05#Pass',
    role: 'user',
    extras: {
      nickname: 'GoldenWhale',
      firstName: 'Sophia',
      lastName: 'Martinez',
      country: 'ES',
      city: 'Madrid',
      balance: 2100,
      casinoBalance: 875,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-06',
    email: 'user06@dodepus.com',
    password: 'User06#Pass',
    role: 'user',
    extras: {
      nickname: 'VividCobra',
      firstName: 'Noah',
      lastName: 'Kim',
      country: 'KR',
      city: 'Seoul',
      balance: 640,
      casinoBalance: 95,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-07',
    email: 'user07@dodepus.com',
    password: 'User07#Pass',
    role: 'user',
    extras: {
      nickname: 'CrimsonWolf',
      firstName: 'Amelia',
      lastName: 'Frost',
      country: 'UK',
      city: 'London',
      balance: 1320,
      casinoBalance: 410,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-08',
    email: 'user08@dodepus.com',
    password: 'User08#Pass',
    role: 'user',
    extras: {
      nickname: 'AzureDragon',
      firstName: 'Hiro',
      lastName: 'Tanaka',
      country: 'JP',
      city: 'Osaka',
      balance: 1880,
      casinoBalance: 530,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-09',
    email: 'user09@dodepus.com',
    password: 'User09#Pass',
    role: 'user',
    extras: {
      nickname: 'EmeraldLion',
      firstName: 'Chloe',
      lastName: 'Nguyen',
      country: 'VN',
      city: 'Da Nang',
      balance: 720,
      casinoBalance: 150,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-10',
    email: 'user10@dodepus.com',
    password: 'User10#Pass',
    role: 'user',
    extras: {
      nickname: 'IronJackal',
      firstName: 'Lucas',
      lastName: 'Anders',
      country: 'SE',
      city: 'Stockholm',
      balance: 960,
      casinoBalance: 205,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-11',
    email: 'user11@dodepus.com',
    password: 'User11#Pass',
    role: 'user',
    extras: {
      nickname: 'QuantumAce',
      firstName: 'Ava',
      lastName: 'Patel',
      country: 'IN',
      city: 'Goa',
      balance: 1430,
      casinoBalance: 480,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-12',
    email: 'user12@dodepus.com',
    password: 'User12#Pass',
    role: 'user',
    extras: {
      nickname: 'SolarViper',
      firstName: 'Ethan',
      lastName: 'Williams',
      country: 'AU',
      city: 'Sydney',
      balance: 1575,
      casinoBalance: 600,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-13',
    email: 'user13@dodepus.com',
    password: 'User13#Pass',
    role: 'user',
    extras: {
      nickname: 'CrystalSphinx',
      firstName: 'Layla',
      lastName: 'Haddad',
      country: 'AE',
      city: 'Dubai',
      balance: 2010,
      casinoBalance: 910,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-14',
    email: 'user14@dodepus.com',
    password: 'User14#Pass',
    role: 'user',
    extras: {
      nickname: 'FrostBadger',
      firstName: 'Mateo',
      lastName: 'Costa',
      country: 'AR',
      city: 'Buenos Aires',
      balance: 890,
      casinoBalance: 170,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-15',
    email: 'user15@dodepus.com',
    password: 'User15#Pass',
    role: 'user',
    extras: {
      nickname: 'VelvetPhoenix',
      firstName: 'Giulia',
      lastName: 'Bianchi',
      country: 'IT',
      city: 'Milan',
      balance: 1340,
      casinoBalance: 365,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-16',
    email: 'user16@dodepus.com',
    password: 'User16#Pass',
    role: 'user',
    extras: {
      nickname: 'IvoryShark',
      firstName: 'Jacob',
      lastName: 'Miller',
      country: 'US',
      city: 'Miami',
      balance: 1180,
      casinoBalance: 295,
      emailVerified: true,
    },
  },
  {
    id: 'seed-user-17',
    email: 'user17@dodepus.com',
    password: 'User17#Pass',
    role: 'user',
    extras: {
      nickname: 'RubyPanda',
      firstName: 'Nora',
      lastName: 'Khan',
      country: 'PK',
      city: 'Karachi',
      balance: 760,
      casinoBalance: 130,
      emailVerified: true,
    },
  },
  {
    id: 'seed-moder-01',
    email: 'Moder1@moder.com',
    password: 'Moder1@moder.com',
    role: 'moderator',
    extras: {
      nickname: 'ModMaster',
      firstName: 'Victor',
      lastName: 'Hayes',
      country: 'US',
      city: 'Austin',
      balance: 5020,
      casinoBalance: 2450,
      mfaEnabled: true,
      emailVerified: true,
    },
  },
  {
    id: 'seed-admin-01',
    email: 'Admin1@admin.com',
    password: 'Admin1@admin.com',
    role: 'admin',
    extras: {
      nickname: 'AdminAces',
      firstName: 'Helena',
      lastName: 'Graves',
      country: 'DE',
      city: 'Berlin',
      balance: 7250,
      casinoBalance: 4100,
      mfaEnabled: true,
      emailVerified: true,
    },
  },
  {
    id: 'seed-owner-01',
    email: 'Ownder1@ownder.com',
    password: 'Ownder1@ownder.com',
    role: 'owner',
    extras: {
      nickname: 'HouseBoss',
      firstName: 'Leon',
      lastName: 'Hartmann',
      country: 'CH',
      city: 'Zurich',
      balance: 15000,
      casinoBalance: 10000,
      mfaEnabled: true,
      emailVerified: true,
    },
  },
];

export const PRESET_ACCOUNTS = enrichAccountsWithTransactions(BASE_ACCOUNTS);
