import { enrichAccountsWithTransactions } from './transactionsSeed';

const BASE_ACCOUNTS = [
  {
    id: 'seed-user-01',
    email: 'user01@dodepus.com',
    password: 'User01#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-02',
    email: 'user02@dodepus.com',
    password: 'User02#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-03',
    email: 'user03@dodepus.com',
    password: 'User03#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-04',
    email: 'user04@dodepus.com',
    password: 'User04#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-05',
    email: 'user05@dodepus.com',
    password: 'User05#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-06',
    email: 'user06@dodepus.com',
    password: 'User06#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-07',
    email: 'user07@dodepus.com',
    password: 'User07#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-08',
    email: 'user08@dodepus.com',
    password: 'User08#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-09',
    email: 'user09@dodepus.com',
    password: 'User09#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-10',
    email: 'user10@dodepus.com',
    password: 'User10#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-11',
    email: 'user11@dodepus.com',
    password: 'User11#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-12',
    email: 'user12@dodepus.com',
    password: 'User12#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-13',
    email: 'user13@dodepus.com',
    password: 'User13#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-14',
    email: 'user14@dodepus.com',
    password: 'User14#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-15',
    email: 'user15@dodepus.com',
    password: 'User15#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-16',
    email: 'user16@dodepus.com',
    password: 'User16#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-user-17',
    email: 'user17@dodepus.com',
    password: 'User17#Pass',
    role: 'user',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      emailVerified: false,
    },
  },
  {
    id: 'seed-moder-01',
    email: 'Moder1@moder.com',
    password: 'Moder1@moder.com',
    role: 'moderator',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      mfaEnabled: false,
      emailVerified: false,
    },
  },
  {
    id: 'seed-admin-01',
    email: 'Admin1@admin.com',
    password: 'Admin1@admin.com',
    role: 'admin',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      mfaEnabled: false,
      emailVerified: false,
    },
  },
  {
    id: 'seed-owner-01',
    email: 'Ownder1@ownder.com',
    password: 'Ownder1@ownder.com',
    role: 'owner',
    extras: {
      nickname: null,
      firstName: null,
      lastName: null,
      country: null,
      city: null,
      balance: 0,
      casinoBalance: 0,
      mfaEnabled: false,
      emailVerified: false,
    },
  },
];

export const PRESET_ACCOUNTS = enrichAccountsWithTransactions(BASE_ACCOUNTS);
