export const ADMIN_NAV_ITEMS = [
  { key: 'overview', to: 'overview', label: 'Обзор', permission: 'overview' },
  { key: 'clients', to: 'clients', label: 'Клиенты', permission: 'clients' },
  { key: 'verification', to: 'verification', label: 'Верификация', permission: 'verification' },
  { key: 'transactions', to: 'transactions', label: 'Транзакции', permission: 'transactions' },
  { key: 'divider-1', type: 'divider' },
  { key: 'promocodes', to: 'promocodes', label: 'Promo', permission: 'promocodes' },
  {
    key: 'promocode-create',
    to: 'promocode-create',
    label: 'Создать Promo',
    permission: 'promocodes',
  },
  {
    key: 'promocode-archive',
    to: 'promocode-archive',
    label: 'Архив Promo',
    permission: 'promocodes',
  },
  { key: 'divider-2', type: 'divider' },
  { key: 'roles', to: 'roles', label: 'Выдать роль', permission: 'roles' },
  { key: 'role-edit', to: 'role-edit', label: 'Изменить роль', permission: 'roles' },
  { key: 'rank-editor', to: 'rank-editor', label: 'Ранг редактор', permission: 'ranks' },
  { key: 'divider-3', type: 'divider' },
  { key: 'moderators-chat', to: 'moderators-chat', label: 'Модератор Чат', permission: 'chat' },
  { key: 'administrators-chat', to: 'administrators-chat', label: 'Админ Чат', permission: 'chat' },
  { key: 'staff-chat', to: 'staff-chat', label: 'Стаф Чат', permission: 'chat' },
  { key: 'divider-4', type: 'divider' },
  { key: 'log-admin', to: 'log-admin', label: 'Log Admin', permission: 'adminPanel' },
];
