import {
  AUTH_USERS_TABLE,
  DEFAULT_AUTH_STATUS,
  PROFILES_TABLE,
} from '../auth/index.js';

export { AUTH_USERS_TABLE, PROFILES_TABLE };

export const DEFAULT_CLIENT_STATUS = DEFAULT_AUTH_STATUS;
